### ISSUE TITLE
What is the systemd timer for?

### ISSUE THREAD

**Issue by marktheunissen** [kerberos-io/documentation#2] opened 2015-06-10 21:02 UTC
Hey there, in the documentation there is a recommendation that a `.timer` file is used to start 1 minute after boot. Any reason for choosing this interval? The .timer could be omitted and the service will just start if it is linked from the right directory, use `After=` to specify what it should start after.

**Comment by cedricve** [comment] 2015-06-11 07:42
Hey Mark, this is a simple hack for the `ntpd` service. I've tried to use `After=` in combination with ntdp, but that didn't worked for me (some months ago).

The problem is that when kerberos is started, it will take a test image without doing processing; 
this image is marked with a timestamp independent from the timezone. If he time isn't synced before the image is taken, it will result in a date 1970-01-01.

I do agree, that this issue could be resolved with the correct configuration, however until now I didn't had the time to do so.

Thanks for your critical view :+1:

**Comment by cedricve** [comment] 2015-09-15 08:56
This is nog resolved and available in the latest image.

**Closed by cedricve** 2015-09-15 08:56 UTC
Labels: enhancement
